stages:
  - prepare
  - test
  - build
  - publish


build_protobuf:
  except:
    - xce
  stage: prepare
  image:
    name: node:14-buster-slim
  cache:
    - key:
        files:
          - messages/proto/messages.proto
      paths:
        - front/src/Messages
  script:
    - cd messages
    - yarn install
    - yarn run proto
    - yarn run copy-to-front
    - yarn run json-copy-to-front
  artifacts:
    paths:
      - front/src/Messages


.test_template: &test_template
  except:
    - xce
  stage: test
  image:
    name: node:14-buster-slim
  dependencies:
    - build_protobuf
  cache:
    - key:
        files:
          - front/yarn.lock
      paths:
        - front/.yarn-cache/

test_build:
  <<: *test_template
  script:
    - cd front
    - yarn install --cache-folder .yarn-cache
    - ./templater.sh
    - export PUSHER_URL="//localhost:8080"
    - export ADMIN_URL="//localhost:80"
    - yarn run build

svelte_check:
  <<: *test_template
  script:
    - cd front
    - yarn install --cache-folder .yarn-cache
    - yarn run svelte-check

lint:
  <<: *test_template
  script:
    - cd front
    - yarn install --cache-folder .yarn-cache
    - yarn run lint

pretty_check:
  <<: *test_template
  script:
    - cd front
    - yarn install --cache-folder .yarn-cache
    - yarn run pretty-check

test:
  <<: *test_template
  script:
    - cd front
    - yarn install --cache-folder .yarn-cache
    - yarn test


.build_template: &build_template
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

.script_template: &script_template
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - export TAG="${DOCKER_TAG}-latest"
  - >-
    /kaniko/executor
    --context "${CI_PROJECT_DIR}"
    --dockerfile "${CI_PROJECT_DIR}/front/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}/wa_front:${TAG}"
    --label=commit=${CI_COMMIT_SHA}
    --label=branch=${CI_COMMIT_REF_SLUG}
    --label=pipeline=${CI_PIPELINE_ID}
    --build-arg=PUSHER_URL=$PUSHER_URL
    --build-arg=ADMIN_URL=$ADMIN_URL
    --build-arg=MAPS_URL=$MAPS_URL
    --build-arg=UPLOADER_URL=$UPLOADER_URL
    --build-arg=START_ROOM_URL=$START_ROOM_URL
    --build-arg=JITSI_PRIVATE_MODE=$JITSI_PRIVATE_MODE
    --build-arg=JITSI_URL=$JITSI_URL
    --build-arg=STUN_SERVER=$STUN_SERVER
    --build-arg=TURN_SERVER=$TURN_SERVER
    --build-arg=TURN_USER=$TURN_SERVER
    --build-arg=TURN_PASSWORD=$TURN_PASSWORD
    --build-arg=MAX_USERNAME_LENGTH=$MAX_USERNAME_LENGTH
    --build-arg=MAX_PER_GROUP=$MAX_PER_GROUP
    --build-arg=DISABLE_NOTIFICATIONS=$DISABLE_NOTIFICATIONS
    --build-arg=SKIP_RENDER_OPTIMIZATIONS=$SKIP_RENDER_OPTIMIZATIONS
    --build-arg=DISPLAY_TERMS_OF_USE=$DISPLAY_TERMS_OF_USE
    --build-arg=CONTACT_URL=$CONTACT_URL
    
build_dev:
  <<: *build_template
  except:
    - xce
    - schedules
  variables:
      DOCKER_TAG: dev
      PUSHER_URL: $PUSHER_URL_DEV
      ADMIN_URL: $ADMIN_URL_DEV
      MAPS_URL: $MAPS_URL_DEV
      UPLOADER_URL: $UPLOADER_URL_DEV
      START_ROOM_URL: $START_ROOM_URL_DEV
      JITSI_PRIVATE_MODE: $JITSI_PRIVATE_MODE
      JITSI_URL: $JITSI_URL
      STUN_SERVER: $STUN_SERVER
      TURN_SERVER: $TURN_SERVER
      TURN_USER: $TURN_USER
      TURN_PASSWORD: $TURN_PASSWORD
      MAX_USERNAME_LENGTH: 20
      MAX_PER_GROUP: 5
      DISABLE_NOTIFICATIONS: "true"
      SKIP_RENDER_OPTIMIZATIONS: "false"
      DISPLAY_TERMS_OF_USE: "false"
      CONTACT_URL: $CONTACT_URL
  script:
    *script_template

build_staging:
  <<: *build_template
  only:
    - xce
  variables:
      DOCKER_TAG: staging
      PUSHER_URL: $PUSHER_URL_STAGING
      ADMIN_URL: $ADMIN_URL_STAGING
      MAPS_URL: $MAPS_URL_STAGING
      UPLOADER_URL: $UPLOADER_URL_STAGING
      START_ROOM_URL: $START_ROOM_URL_STAGING
      JITSI_PRIVATE_MODE: $JITSI_PRIVATE_MODE
      JITSI_URL: $JITSI_URL
      STUN_SERVER: $STUN_SERVER
      TURN_SERVER: $TURN_SERVER
      TURN_USER: $TURN_USER
      TURN_PASSWORD: $TURN_PASSWORD
      MAX_USERNAME_LENGTH: 20
      MAX_PER_GROUP: 5
      DISABLE_NOTIFICATIONS: "true"
      SKIP_RENDER_OPTIMIZATIONS: "false"
      DISPLAY_TERMS_OF_USE: "false"
      CONTACT_URL: $CONTACT_URL
  script:
    *script_template


build_prod:
  <<: *build_template
  only:
    - xce
  variables:
      DOCKER_TAG: prod
      PUSHER_URL: $PUSHER_URL_PROD
      ADMIN_URL: $ADMIN_URL_PROD
      MAPS_URL: $MAPS_URL_PROD
      UPLOADER_URL: $UPLOADER_URL_PROD
      START_ROOM_URL: $START_ROOM_URL_PROD
      JITSI_PRIVATE_MODE: $JITSI_PRIVATE_MODE
      JITSI_URL: $JITSI_URL_PROD
      STUN_SERVER: $STUN_SERVER_PROD
      TURN_SERVER: $TURN_SERVER_PROD
      TURN_USER: $TURN_USER_PROD
      TURN_PASSWORD: $TURN_PASSWORD_PROD
      MAX_USERNAME_LENGTH: 20
      MAX_PER_GROUP: 5
      DISABLE_NOTIFICATIONS: "true"
      SKIP_RENDER_OPTIMIZATIONS: "false"
      DISPLAY_TERMS_OF_USE: "false"
      CONTACT_URL: $CONTACT_URL
  script:
    *script_template

